---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openresty-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: openresty-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: openresty-ingress
spec:
  template:
    metadata:
      labels:
        k8s-app: openresty-ingress
        name: openresty-ingress
    spec:
      serviceAccountName: openresty-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: maartje/k8s-openresty-ingress
        tag: arm64-latest
        name: openresty-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443

---
kind: Service
apiVersion: v1
metadata:
  name: openresty-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: openresty-ingress
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
  type: NodePort
